### ISSUE TITLE
Language handling

### ISSUE THREAD

**Issue by yukosgiti** [Proskynete/vertical-timeline-component-react#31]
To handle the dates in many different languages, modern browsers support the  `toLocaleDateString()` method. If you can utilise this mehod, you can automatically support all available languages. [Here are the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

**Comment by Proskynete** [comment]
Oh perfect! thank you so much!
I will work to incorporate it
