### ISSUE TITLE
Can you remove that freakin console.log(_lang)?

### ISSUE THREAD

**Issue by yunkhngn** [Proskynete/vertical-timeline-component-react#48]
Can you remove that freakin console.log(_lang)? It's so annoying.

![image](https://user-images.githubusercontent.com/44545000/165357076-270e6ba5-a863-45d2-a6d7-af4248ca73b6.png)

**Comment by Proskynete** [comment]
Damn! I hadn't realized. Thank you so much @yunkhngn!
