### ISSUE TITLE
Next.js compatibility/error: window is not defined

### ISSUE THREAD

**Issue by advaitju** [Proskynete/vertical-timeline-component-react#9]
When using this component in Next.js I get the error **window is not defined**.

Since it is server side, there is no _window_ element for React.

Just a suggestion, I think the component should be modified so a call to _window_ is made in _componentDidMount()_, where you can access the _window_ object. It'd make it more versatile.

For now I'm importing the CSS and replacing the component JSX with HTML that is output in the browser.

**Comment by Proskynete** [comment]
@advaitju excuse the delay of the answer. Now I'm going to review it to fix it

**Comment by daddyj** [comment]
Any updates on this? Would love to use it in my nextjs project. Big up for the work so far! 👍

**Comment by Proskynete** [comment]
@daddyj I'm currently working on this error. When it's fixed, I'll let you know. 
Thanks so much for you interested :D

**Comment by Proskynete** [comment]
@advaitju @daddyj, This issue is fixed in the last version, Thanks so much for waiting for this fix

**Comment by daddyj** [comment]
Cheers for the updates @Proskynete - will test it today! 🚀
